### PR TITLE
Profiles UI

### PR DESCRIPTION
**Pull request by albatrocity**

### CODE REVIEW

**Comment by albatrocity** [comment]
@roblafeve I got lazy on #5 and am just going to use gravatar for now. Don't want to mess with cross-domain ajaxy file uploads yet.

The rest is ready to be styled up. This PR fixes a lot of issues in general, so it should go into master soon. Avatar images were still showing up large for me so I'm only pulling back 80x80 from Gravatar. You can change the size it pulls back in `view-helper.coffee` by [appending a](http://en.gravatar.com/site/implement/images/) `?s=` to the [gravatar url string](https://github.com/cremalab/engagement-ring/blob/4e3bda40eaaf83e27344d24bda21231cf5f08ecd/app/lib/view-helper.coffee#L45).

**Comment by roblafeve** [comment]
Sounds good. The image size thing sounds like something I need to fix. Thanks.

**Comment by albatrocity** [comment]
@roblafeve can I merge this in so I can get it deployed onto Heroku? You can open a separate PR for styling.

**Comment by roblafeve** [comment]
@albatrocity, do it

**Pull request merged**
